### ISSUE TITLE
Fantasy theme

### ISSUE THREAD

**Issue by erlend-sh** [lampe-games/godot-open-rts#101]
The two most common themes of RTS games are sci-if and medieval/fantasy, so it’d be nice to have an example of the latter as well. Thankfully there are some great CC0 assets available!

![](https://quaternius.com/assets/images/fullres/ultimatefantasyrts.jpg)

Main RTS pack:
https://quaternius.com/packs/ultimatefantasyrts.html

Nature assets:
https://quaternius.com/packs/ultimatestylizednature.html

Human units:
https://quaternius.com/packs/ultimatemodularcharacters.html
https://quaternius.com/packs/ultimatemodularwomen.html

Music:
https://alkakrab.itch.io/free-25-fantasy-rpg-game-tracks-no-copyright-vol-2

SFX:
https://leohpaz.itch.io/minifantasy-dungeon-sfx-pack
https://leohpaz.itch.io/minifantasy-forgotten-plains-sfx-pack

**Comment by Scony** [comment]
Thanks for bringing those asset links - that may be useful.

As for the themes, I think having multiple ones is out of the scope of this project - that would require a lot of work to unify units, HUD, UI, maps, music, SFX, balance etc. There's still a lot to do to fully support the current theme. Anyway, that's definitely a good idea for a fork.
