### ISSUE TITLE
Resurrectable Units

### ISSUE THREAD

**Issue by sta17** [lampe-games/godot-open-rts#113]
Having an ability to resurrect story important units, somehow is really useful. Notices the absence in Age of Empire 2, where you might have important named character, but once they die, they have to be recreated and all the threads be restitched together, which is unnecessary, so having this in could be useful. Especially since its supposed to be similar to a demo per my understanding.

There are different ways of doing it, like Age of Mythology, where there is a body on the ground, until the player has units near it again and the hp regeneration kicks in, or like Warcraft 3, where you pay a fee and click a button like any other unit producing / train, to get it back. I just remembered the limitation in comparison to Age of Empire 2 vs Warcraft 3.

It is not important in standard RTS gameplay if it is not character based, but in campaigns and story, character management, and management of special units, are more important.

**Comment by Scony** [comment]
Originally I've been thinking about introducing such a "hero" units but eventually I've decided it's beyond the scope of this project. In this project I'm aiming to introduce a fairly minimal baseline - and I'm still not there yet, so I'll be focusing rather on that.
