### ISSUE TITLE
weird worker rotation when collecting resources

### ISSUE THREAD

**Issue by Scony** [lampe-games/godot-open-rts#39]
when a worker is collecting resources and is being poked by some unit passing by, it maintains rotation that is not pointing exactly at the resource it's harvesting

**Comment by Bazsi1224** [comment]
Hi there,
could you write a little description, what do the workers wrong, and what do you expect them to do.

**Comment by Scony** [comment]
Sure, done.

**Comment by Bazsi1224** [comment]
May I add working animation here ( I mean GPUparticle sparks )?
Or shall I make a separate issue PR combo?

**Comment by Scony** [comment]
> May I add working animation here ( I mean GPUparticle sparks )? Or shall I make a separate issue PR combo?

Let's add it as a separate PR as this is clearly a unrelated feature
