### ISSUE TITLE
Add rally flags for unit factories

### ISSUE THREAD

**Issue by Bazsi1224** [lampe-games/godot-open-rts#52]

**Comment by Scony** [comment]
what do you mean by rally flags? can you elaborate?

**Comment by Bazsi1224** [comment]
I meant a position for unit creating buildings, where each freshly created unit will go after spawning.
So your unit does not stack up around the creator building.

And yes, I can try to do it for you.

**Comment by Scony** [comment]
Oh, yes, that's a good idea - I forgot about it, while it's one of the core RTS mechanics.
