### ISSUE TITLE
Multiplayer?

### ISSUE THREAD

**Issue by poVoq** [lampe-games/godot-open-rts#64]
Are there plans to add Vs. and coop multiplayer?

**Comment by Scony** [comment]
Not for now. Since I'd like to keep this project as simple as possible, multiplayer etc. should not be done as long as the core part is not fully finished and polished.
Therefore at some point it may potentially be added, but that's a distant future.

**Comment by Cyber-Morpheous** [comment]
@Scony  Can you guide me on how to add Multiplayer

**Comment by Scony** [comment]
@Cyber-Morpheous that's very hard to explain briefly, but to put simply - you'd need to create a new type of player similar to AI one, but "Remote" one that would be syncing state of remote players. At the same time, the "Human" player would have to be extended to smth like "RemoteSyncedHuman" that would send it's state to the server. Then ofc. the hardest part is how to design syncing itself, how to design server etc. That's fairly complicated and also there are multiple design possibilities so I'll not go any further.
