### ISSUE TITLE
UI too small / UI scaling?

### ISSUE THREAD

**Issue by domenukk** [lampe-games/godot-open-rts#65]
When trying the Game on my 14 inch Macbook the UI is _way_ too small.
It'd be nice to scale the UI somehow.
Imagine this on a 14 inch laptop:
<img width="1512" alt="image" src="https://github.com/lampe-games/godot-open-rts/assets/297744/da460ec8-393d-46e2-bbe9-9bf6d6216777">

**Comment by domenukk** [comment]
Just setting `Window>Mode` to `canvas_items` in project settings already helped

**Comment by Scony** [comment]
thanks, I'll check what would be the best way to address that
