### ISSUE TITLE
Lack of animation when resources are consumed

### ISSUE THREAD

**Issue by domenukk** [lampe-games/godot-open-rts#67]
We spawn with three blue and one red resources.
One of the three blue resources disappears sometimes, the other ones don't.
Not sure if that's a bug?

**Comment by Scony** [comment]
no - one of the resources contains fewer crystals and therefore is consumed pretty fast.
Anyway, this is a good moment to introduce some animation not to confuse the players.

**Comment by domenukk** [comment]
Could also be nice to see how many resources are in a container somehow

**Comment by Scony** [comment]
> Could also be nice to see how many resources are in a container somehow

right, some HUD for units/resources must be added at some point. I've added #77 for tracking
