### ISSUE TITLE
Right edge doesn't scroll (MacOS 14 inch)

### ISSUE THREAD

**Issue by domenukk** [lampe-games/godot-open-rts#76]
On my machine the upper, left, and lower edges scroll just fine, the right edge doesn't scroll, no matter how much to the right I move.
Let me know if there's some way I can help debug this.

**Comment by domenukk** [comment]
Similar behavior in windowed mode, actually: The mouse has to be out of the game completely to scroll, see video:
https://github.com/lampe-games/godot-open-rts/assets/297744/47501399-18fe-4b51-8c3c-ba8bb225b498

Restricting the mouse to the game window (in settings) doesn't help but makes it so that the mouse sometimes moves to the left by itself when moving it to the right at the right edge.

**Comment by domenukk** [comment]
Similar behavior in windowed mode, actually: The mouse has to be out of the game completely to scroll, see video.

Restricting the mouse to the game window (in settings) doesn't help but makes it so that the mouse sometimes moves to the left by itself when moving it to the right at the right edge.

https://github.com/lampe-games/godot-open-rts/assets/297744/3845bdc1-4493-4666-9886-dbc53c601fca

**Comment by Scony** [comment]
@domenukk can you try increasing `screen_margin_for_movement` of `IsometricCamera3D` of `res://source/match/Match.tscn` ?

**Comment by domenukk** [comment]
Setting it to `2` helped.

Related, the "Restrict the mouse" option seems pretty broken though, also unrelated to the scroll behavior. When set, the mouse sometimes moves up when I try to move down. I can open an extra bug for that if it helps (hard to explain, though)

**Comment by Scony** [comment]
@domenukk feel free to create separate ticket for that
