### ISSUE TITLE
Selection of starting units doesn't work

### ISSUE THREAD

**Issue by berndrakell** [lampe-games/godot-open-rts#94]
When I run the game and select one of my starting units they appear to be selected but the unit menu doesn't open and they are not moveable.

![grafik](https://github.com/lampe-games/godot-open-rts/assets/26837091/82f2c476-7779-4180-a5d8-994b9735b677)

**Comment by berndrakell** [comment]
The problem for this lays in Match.gd function 

func _setup_and_spawn_unit()

where _setup_unit_groups(unit) is called before player.add_child(unit). In _setup_unit_groups(unit) the player of the unit must be evaluated to assign it to the correct group. As the unit node does not have a parent yet, the player is returned as null and the unit is not identified as belonging to the human player

**Comment by Scony** [comment]
Right, this is a regression introduced in recent refactoring - it was tested using the manual test with predefined units only... Thanks for reporting!
